name: Continuous Integration. E2E

env:
  # APP
  APP_URL: http://localhost:3000
  # DB
  POSTGRESQL_VERSION: 14.1
  DB_NAME: e2edb
  DB_USER: postgres
  DB_PASSWORD: 12345
  DB_HOST: localhost


on:
  pull_request:
    branches:
      - production
      - development

jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:12
        # Provide the password for postgres
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      # - name: Tests Code Checkout
      #   uses: actions/checkout@v2
      #   with:
      #     repository: what1s1ove/e2e-double-repos-playwright
      #     path: ./tests

      # - name: Install NodeJS
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version-file: .nvmrc

      # - name: Install PostgreSQL
      #   uses: CasperWA/postgresql-action@v1.2
      #   with:
      #     postgresql version: '12.2'
      #     postgresql user: "test"
      #     postgresql db: "test"
      #     postgresql password: "password"
      #     postgresql auth: trust
      #     postgresql port: 1488

      - name: Check LS
        run: |
          ls
          psql -V

      - name: Restore Backup PostgreSQL
        uses: tj-actions/pg-restore@v4.5
        with:
          database_url: "postgres://test:password@localhost:5432/test"
          backup_file: "./schema.sql"

      - name: Install Dependencies
        run: |
          npm i

      - name: Tests Install Dependencies
        working-directory: ./tests
        run: |
          npm i
          npx playwright install --with-deps

      - name: Start Application
        run: |
          npm start & npx wait-on ${{ env.APP_URL }}

      - name: E2E
        working-directory: ./tests
        run: |
          npm run test
