name: Continuous Integration. E2E

on:
  pull_request:
    branches:
      - production
      - development

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout Code
        uses: actions/checkout@v2

      - name: Code Checkout Tests Code
        uses: actions/checkout@v2
        with:
          repository: what1s1ove/e2e-double-repos-playwright
          path: ./tests

      - name: Check sources
        run: |
          ls
          cd ./tests
          ls

      # - name: Install NodeJS
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version-file: .nvmrc

      # - name: Install Dependencies
      #   run: |
      #     npm run install:all

      # - name: Install Playwright Browsers
      #   working-directory: ./tests
      #   run: npx playwright install --with-deps

      # - name: E2E
      #   run: |
      #     npm run test
