name: Continuous Integration. E2E

on:
  pull_request:
    branches:
      - production
      - development

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Tests Code Checkout
        uses: actions/checkout@v2
        with:
          repository: what1s1ove/e2e-double-repos-playwright
          path: ./tests

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version-file: .nvmrc

      - name: Install Dependencies
        run: |
          npm i

      - name: Tests Install Dependencies
        working-directory: ./tests
        run: |
          npm i
          npx playwright install --with-deps

      - name: Start Application
        run: |
          npm start & npx wait-on http://localhost:3000

      - name: E2E
        working-directory: ./tests
        run: |
          npm run test
