name: Continuous Integration. E2E

env:
  # APP
  APP_URL: http://localhost:3000
  # DB
  POSTGRESQL_VERSION: 14.2
  DB_NAME: e2edb
  DB_USER: postgres
  DB_PASSWORD: 12345
  DB_HOST: localhost


on:
  pull_request:
    branches:
      - production
      - development

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Tests Code Checkout
        uses: actions/checkout@v2
        with:
          repository: what1s1ove/e2e-double-repos-playwright
          path: ./tests

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version-file: .nvmrc

      - name: Install PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql version: ${{ env.POSTGRESQL_VERSION }}
          postgresql db: ${{ env.DB_NAME }}
          postgresql user: ${{ env.DB_USER }}
          postgresql password: ${{ env.DB_PASSWORD }}

      - name: Check connection str
        run: |
          echo "postgres://${{ env.DB_USER }}:${{ env.DB_PASSWORD }}@${{ env.DB_HOST }}:5432/${{ env.DB_NAME }}"


      - name: Restore Backup PostgreSQL
        run: |
          psql ${{ env.DB_NAME }} < schema.sql

      - name: Install Dependencies
        run: |
          npm i

      - name: Tests Install Dependencies
        working-directory: ./tests
        run: |
          npm i
          npx playwright install --with-deps

      - name: Start Application
        run: |
          npm start & npx wait-on ${{ env.APP_URL }}

      - name: E2E
        working-directory: ./tests
        run: |
          npm run test
